language: node_js
node_js:
- 7
jobs:
  include:
  - stage: validate
    script:
    - echo $TRAVIS_TAG
  - stage: install
    script:
    - npm install
  - stage: test
    install: skip
    script:
    - npm install -g codecov
    - npm test
    - codecov --token=2d6f5593-63fe-418d-aaed-fa7c2f82c0eb
  - stage: deploy
    install: skip
    script: skip
    deploy:
      - provider: npm
        email: fdf8210@gmail.com
        api_key:
          secure: Ga+E9X02gB/VmED8759bYA6Z3EgC8ds2mOdmmfXw8o86p9jgWIuCKBrVuqSoYCul3cnWhb5Vg9jQFqH1jbkw7qsykq3gPxmA7/XVSphU6dRr0BXS4Pf5tLyX2Pnoe3wavJwgIFf/qoRqd98NTID6sDPQxqymeWLYSxW6D/9mLrv+fY682OvXkrxdWo5nxK2E4sNsq6gMbmYNfU1L9IDZG1JdJJEt58s2q1LsF89bPdU1cqhbjST6VwYw4fjHDmLh27je4gOiKBZKSdtL/4dYS9crubyYZIHCRIudnTD8DdXmMTQ0/MMO2diguVTu3UAHOfCxZO+nsUniI583vBYvwox51efGqs6EF05LeGrFFk+9YxtVGj6BvD6q43p95wG+vo51iH/t3idncMGWFngbX7m/SslOSAfaqDYmVlLc8Vgnh9ucR8bZ1gGBLfvDAr7EEwdFYmbG8u6GHt1m98SDaXaVhXoM6kTmS0haarM5kg1fwEk9UhXsuz9xVwHaTVadgEcB0e5WwmMRkVlzijDVbiWMDa2r23KUx/XIOq9T0NDJ1soOb1re9twTr7Df5+917mdLyUzLdo02wUAm4cgZ25xpgE69YLL/Yo0iMHIMtkkFIrWp/Mz5qnEpVbc8iKBuhh8dzwO11HNKfzKhfBl+NInjy0lOB+zwYX9QY9qD24s=
        on:
          repo: fdefelici/hello-npm
          tags: true
          #all_branches: true
          condiction: $TRAVIS_TAG == 1.*
        skip_cleanup: true
        tag: previous
      - provider: npm
        email: fdf8210@gmail.com
        api_key:
          secure: Ga+E9X02gB/VmED8759bYA6Z3EgC8ds2mOdmmfXw8o86p9jgWIuCKBrVuqSoYCul3cnWhb5Vg9jQFqH1jbkw7qsykq3gPxmA7/XVSphU6dRr0BXS4Pf5tLyX2Pnoe3wavJwgIFf/qoRqd98NTID6sDPQxqymeWLYSxW6D/9mLrv+fY682OvXkrxdWo5nxK2E4sNsq6gMbmYNfU1L9IDZG1JdJJEt58s2q1LsF89bPdU1cqhbjST6VwYw4fjHDmLh27je4gOiKBZKSdtL/4dYS9crubyYZIHCRIudnTD8DdXmMTQ0/MMO2diguVTu3UAHOfCxZO+nsUniI583vBYvwox51efGqs6EF05LeGrFFk+9YxtVGj6BvD6q43p95wG+vo51iH/t3idncMGWFngbX7m/SslOSAfaqDYmVlLc8Vgnh9ucR8bZ1gGBLfvDAr7EEwdFYmbG8u6GHt1m98SDaXaVhXoM6kTmS0haarM5kg1fwEk9UhXsuz9xVwHaTVadgEcB0e5WwmMRkVlzijDVbiWMDa2r23KUx/XIOq9T0NDJ1soOb1re9twTr7Df5+917mdLyUzLdo02wUAm4cgZ25xpgE69YLL/Yo0iMHIMtkkFIrWp/Mz5qnEpVbc8iKBuhh8dzwO11HNKfzKhfBl+NInjy0lOB+zwYX9QY9qD24s=
        on:
          repo: fdefelici/hello-npm
          tags: true
          #all_branches: true
          condiction: $TRAVIS_TAG == 2.*
        skip_cleanup: true
        tag: latest
        
stages:
- name: validate
  if: tag IS present
- install
- test
- name: deploy
  #if: tag IS present
  
